version: '3'
services:
  watchlist-web-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: watchlist-web
    ports:
      - 27017:27017
  watchlist-web-frontend:
    image: watchlist-web-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://watchlist-web-backend:8080/
    ports:
      - 3000:3000
  watchlist-web-backend:
    image: watchlist-web-backend:latest
    environment:
      MONGODB_URI: mongodb://watchlist-web-db:27017/watchlist-web
    ports:
      - 8080:8080